<a href="https://colab.research.google.com/github/Dang1994/Pytorch_for_deep_learning/blob/main/my_pytorch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.5.0+cu121


# Introuction to Tensors
### Creating tensors

Pytorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html


In [ ]:
# scalar
scalar =torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
random_tesnor = torch.rand(1, 3, 4)

random_tesnor

tensor([[[0.9208, 0.8808, 0.4848, 0.1831],
         [0.1317, 0.2607, 0.3970, 0.9403],
         [0.4999, 0.4383, 0.8649, 0.9344]]])

In [ ]:
random_image_size_tesnor = torch.rand(size=(224,224,3))

random_image_size_tesnor.shape, random_image_size_tesnor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_tesnor.ndim

2

In [ ]:
zeros = torch.arange(start=3, end =4, step=0.5)
zeros

tensor([3.0000, 3.5000])

In [ ]:
zeros_one = torch.zeros_like(zeros)
zeros_one

tensor([0., 0.])